// <auto-generated />
using System;
using EventosVivos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventosVivos.Infrastructure.Migrations
{
    [DbContext(typeof(EventosVivosDbContext))]
    partial class EventosVivosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventosVivos.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsCanceled");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Events_Title");

                    b.HasIndex("Type");

                    b.HasIndex("VenueId");

                    b.HasIndex("VenueId", "IsCanceled");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("EventosVivos.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Reservations_Code")
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("EventId");

                    b.HasIndex("Status");

                    b.HasIndex("EventId", "Status", "ExpiresAt")
                        .HasDatabaseName("IX_Reservations_EventId_Status_ExpiresAt");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("EventosVivos.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Venues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 200,
                            City = "Bogotá",
                            Name = "Auditorio Central"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            City = "Bogotá",
                            Name = "Sala Norte"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 500,
                            City = "Medellín",
                            Name = "Arena Sur"
                        });
                });

            modelBuilder.Entity("EventosVivos.Domain.Entities.Event", b =>
                {
                    b.HasOne("EventosVivos.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EventosVivos.Domain.ValueObjects.EventSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("EndsAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("EndsAt");

                            b1.Property<DateTimeOffset>("StartsAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("StartsAt");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("EventosVivos.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("EventosVivos.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("EventosVivos.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EventosVivos.Domain.ValueObjects.Buyer", "Buyer", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BuyerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BuyerName");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Buyer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
